version: '3'
services:
  nginx:
    image: nginx:latest
    ports: 
      - "80:80"
    volumes:
      - .:/code
      - ./config/nginx:/etc/nginx/conf.d
      - static-files:/static:rw
    depends_on:
      - ucs

  db:
    image: mariadb:latest
    volumes:
      - ./mariadb/data/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: 'UCS'
    expose:
      - "3306"


  ucs:
    image: ucs_test:0.6
    command: >
            bash -c "sleep 20
            && cd /root/University-Coding-Site/src/Django/ucs/
            && python3 manage.py collectstatic --noinput
            && ./auto_init.sh
            && gunicorn ucs.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static-files:/static:rw
    expose:
      - "8000"
    links:
      - db
    depends_on:
      - db

volumes:
  static-files:
